### ISSUE TITLE
Open Source and Security

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#100]
Description:
Security in Open Source. Address the security aspects of open-source software and how communities work to identify and fix vulnerabilities.

1. Write a Script - Check out the [ samples ](https://docs.google.com/document/d/1zMHxMU28yJeJSoiM_3ieQ5LCA6gVT-oOeJdpbYILjdQ/edit) and use this [template](https://docs.google.com/document/d/1jIee4PRQsjF4_nDBxNOcbAxeQ1WA0w5HKOlRc3wdR34/edit)
2. Create a Slide deck - Find a sample [here](https://github.com/chaoss/education/blob/main/Submission.md), and use this [template](https://docs.google.com/presentation/d/1t_oBQhMAtZvvsqTppRj96fbjpokakjiZOdtWIO3NIdY/edit#slide=id.g224756f3bb6_1_0)
3. Record a video - [Sample](https://github.com/chaoss/education/blob/main/Submission.md) 

**Additional context**

- Kindly go through the [ReadMe.md](https://github.com/chaoss/education/blob/main/README.md) file. 
- [Contributing.md ](https://github.com/chaoss/education/blob/main/Contributing.md)file contains information that will help you get started
- Choose your preferred [background](https://github.com/chaoss/education/blob/main/README.md#video-background) for your video recording.

**Comment by SophiaUgo** [comment]
Hi Peculiar, having gone through the material I would like to work on this, could you please assign me?

**Comment by peculiaruc** [comment]
> Hi Peculiar, having gone through the material I would like to work on this, could you please assign me?

There you

**Comment by peculiaruc** [comment]
@SophiaUgo Thanks for your effort so far. When do you think we conclude on this issue
