### ISSUE TITLE
Contributing as a Designer in Open Source

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#17]
Description:

- Write a Script for Contributing as a Designer in Open Source, using CHAOSS as a case study.
-  How Designers Contribute to open-source projects like CHAOSS Project

 Learn more about contributing to this project [here ](https://github.com/chaoss/education/blob/main/Contributing.md)

 Go through the [ReadMe ](https://github.com/chaoss/education/blob/main/README.md) before you start.

**Comment by iamkingsleey** [comment]
I can handle this @peculiaruc @yigakpoa

**Comment by yigakpoa** [comment]
Thank you @iamkingsleey I have just assigned this to you. We will share the templates to guide you after they have been approved!

**Comment by peculiaruc** [comment]
@iamkingsleey  hi! Just checking in with this.
Do you need any help getting started?
Are you able to work on this issue in the next few weeks?

**Comment by peculiaruc** [comment]
Hi! @iamkingsleey Just checking in with this again. Do you need any help getting started? Are you able to work on this issue in the next few weeks?

**Comment by iamkingsleey** [comment]
So sorry, I missed the comments @peculiaruc going back to working on this.

**Comment by peculiaruc** [comment]
> So sorry, I missed the comments @peculiaruc going back to working on this.

Make a copy and use this [template](https://docs.google.com/document/d/1jIee4PRQsjF4_nDBxNOcbAxeQ1WA0w5HKOlRc3wdR34/edit)

Slide deck, use this [template](https://docs.google.com/presentation/d/1Hhhzau9hc2WJyTbRJWmMFdxFTn4KjBROrevI9JvsZnU/edit#slide=id.g2ab5a4dbc5f_0_5)
