### ISSUE TITLE
Spreadsheet of Content Modules

### ISSUE THREAD

**Issue by yigakpoa** [chaoss/education#2]
We need a spreadsheet of content modules for the Onboarding Course and tasks for each.

**Comment by peculiaruc** [comment]
@yigakpoa The spreadsheet has been prepared. I will create the issues out here  as soon as I get approval for @ElizabethN

**Comment by yigakpoa** [comment]
Oh yes i know, I'm about to create the project board so I intend to use these issues. 

Ps. I added all the first 3 tasks we had ( form, spreadsheet with tasks for each & project board with tasks for each)...

**Comment by peculiaruc** [comment]
> Oh yes i know, I'm about to create the project board so I intend to use these issues.
> 
> Ps. I added all the first 3 tasks we had ( form, spreadsheet with tasks for each & project board with each topic)... @peculiaruc

Great! Send me invite to the project board

**Comment by peculiaruc** [comment]
> Oh yes i know, I'm about to create the project board so I intend to use these issues.
> 
> Ps. I added all the first 3 tasks we had ( form, spreadsheet with tasks for each & project board with each topic)... @peculiaruc

@yigakpoa I will be closing up this issue. It has been concluded

**Comment by yigakpoa** [comment]
@peculiaruc yes, yes.
