### ISSUE TITLE
Process of Contributing to CHAOSS on GitHub

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#20]
Description:

Create a video content:
- About the CHAOSS Org and the repos
- How to find an issue to work on
- How to submit a PR (include DCO)

 Learn more about contributing to this project [here ](https://github.com/chaoss/education/blob/main/Contributing.md)

 Go through the [ReadMe ](https://github.com/chaoss/education/blob/main/README.md) before you start.

**Comment by peculiaruc** [comment]
@kaxada hi! Just checking in with this.
Do you need any help getting started?
Are you able to work on this issue in the next few weeks?

**Comment by kaxada** [comment]
@peculiaruc I am putting this on my calendar for next week 📝

**Comment by peculiaruc** [comment]
> @peculiaruc I am putting this on my calendar for next week 📝

You can have a look at this too https://github.com/chaoss/education#example-materials

**Comment by kaxada** [comment]
@peculiaruc adding that too to my links of reference

**Comment by kaxada** [comment]
@peculiaruc and @yigakpoa to be specific I will work on it on Friday 2nd, Feb

**Comment by kaxada** [comment]
https://github.com/chaoss/education/issues/13

**Comment by peculiaruc** [comment]
> @peculiaruc and @yigakpoa to be specific I will work on it on Friday 2nd, Feb

Hi! @kaxada  Just checking in with this again. Do you need any help getting started? Are you able to work on this issue in the next few weeks?
