### ISSUE TITLE
DEI in Open Source

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#22]
Description:

-  Write Script for DEI in Open Source
- General knowledge about DEI in Open source

 Learn more about contributing to this project [here ](https://github.com/chaoss/education/blob/main/Contributing.md)

 Go through the [ReadMe ](https://github.com/chaoss/education/blob/main/README.md) before you start.

**Comment by Toriasdesign** [comment]
I would love to contribute to this issue

**Comment by peculiaruc** [comment]
@Toriasdesign hi! Just checking in with this.
Do you need any help getting started?
Are you able to work on this issue in the next few weeks?

**Comment by Toriasdesign** [comment]
I already started. Currently working on it.

**Comment by peculiaruc** [comment]
> I already started. Currently working on it.

You could check this out -> https://github.com/chaoss/education#example-materials

**Comment by peculiaruc** [comment]
> I already started. Currently working on it.

Hi! @Toriasdesign  Just checking in with this again. Do you need any help getting started? Are you able to work on this issue in the next few weeks?

**Comment by harmonyelendu** [comment]
I will love to contribute to this Project.

**Comment by peculiaruc** [comment]
Hello, @harmonyelendu  Are you able to complete this issue before the end of this month?

**Comment by harmonyelendu** [comment]
Yes, already working on it and still in progress.

**Comment by harmonyelendu** [comment]
@peculiaruc  here is a link to my script for Review 
https://docs.google.com/document/d/1hYrhEI_bGIvUABVa_mhgcKCMIrL6tDTFuhNZaKKFFOA/edit?usp=sharing

**Comment by peculiaruc** [comment]
> @peculiaruc here is a link to my script for Review https://docs.google.com/document/d/1hYrhEI_bGIvUABVa_mhgcKCMIrL6tDTFuhNZaKKFFOA/edit?usp=sharing

Review is ongoing

**Comment by peculiaruc** [comment]
> @peculiaruc here is a link to my script for Review https://docs.google.com/document/d/1hYrhEI_bGIvUABVa_mhgcKCMIrL6tDTFuhNZaKKFFOA/edit?usp=sharing

You can now go ahead to prepare a Slide deck. Thank you so much

**Comment by harmonyelendu** [comment]
Thank you for the review, will get to it

**Comment by harmonyelendu** [comment]
Hi @peculiaruc Slides are ready and open for review. 
https://docs.google.com/presentation/d/1Xk8IMFJKhkcjgrC2L2hQrQDHI46iYC-ECuro5mVapgc/edit?usp=sharing

**Comment by peculiaruc** [comment]
Thank you @harmonyelendu  for working on this issue
