### ISSUE TITLE
Contributing to Open- Source as a Community Manager

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#24]
- Create a general  video on how one can Contribute to  Open- Source as a Community Manager

**Comment by Maryblessing** [comment]
Hello @peculiaruc

**Comment by Maryblessing** [comment]
Is there a timeline I should be aware of? Delivery time. 
Also, how long should the video be for?

**Comment by peculiaruc** [comment]
> Is there a timeline I should be aware of? Delivery time. Also, how long should the video be for?

I share these with you.

**Comment by Maryblessing** [comment]
You did? I must have missed it. Please share again

**Comment by peculiaruc** [comment]
@Maryblessing hi! Just checking in with this.
Do you need any help getting started?
Are you able to work on this issue in the next few weeks?

**Comment by peculiaruc** [comment]
> Is there a timeline I should be aware of? Delivery time. Also, how long should the video be for?

Hi! @Maryblessing Just checking in with this again. Do you need any help getting started? Are you able to work on this issue in the next few weeks?
