### ISSUE TITLE
Edit Recorded Videos for the Onboarding Course

### ISSUE THREAD

**Issue by yigakpoa** [chaoss/education#25]
- Help edit already recorded video content with video editing softwares.

**Comment by peculiaruc** [comment]
@yigakpoa I am thinking this issue is not documentation. Maybe the label could be removed. It has be be editing the video with any video editing platform not writing about the the video. What do you think?

**Comment by yigakpoa** [comment]
Hi @peculiaruc Thats a good point. 
What label do you suggest we add to this? Or maybe remove the label altogether since its a one time thing? Because I don’t think there’s a “fitting”  label per se for video editing. 

I also think that the issue itself is self explanatory, the label is just for better organization in the Project board. But if you have better ideas i’m open to it.

**Comment by peculiaruc** [comment]
I will think of something.  I get back to you on this

**Comment by yigakpoa** [comment]
Awesome! I’ll be waiting…
