### ISSUE TITLE
Write Script for CHAOSS Context Working Groups Video

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#34]
Description:

- Write  Script for CHAOSS Context Working Group Video
- See [guideline](https://docs.google.com/document/d/1jIee4PRQsjF4_nDBxNOcbAxeQ1WA0w5HKOlRc3wdR34/edit)

**Comment by germonprez** [comment]
This is complete at: https://docs.google.com/document/d/1zMHxMU28yJeJSoiM_3ieQ5LCA6gVT-oOeJdpbYILjdQ/edit

**Comment by germonprez** [comment]
@peculiaruc
