### ISSUE TITLE
Write Script for CHAOSS Governance Video

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#37]
Description:

- Write Script for CHAOSS Governance Video
- See [guideline](https://docs.google.com/document/d/1jIee4PRQsjF4_nDBxNOcbAxeQ1WA0w5HKOlRc3wdR34/edit)

**Comment by geekygirldawn** [comment]
Here's the script for the governance video: https://docs.google.com/document/d/1xl5Mi0YKTF-hr44Wf7TK3Zv5bKARw_eY6PERx2YVr0M/preview

**Comment by geekygirldawn** [comment]
This step has been completed.
