### ISSUE TITLE
Edit CHAOSS Context Working Groups Video

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#46]
Description: 
- Edit CHAOSS Context Working Group recorded video content with video editing software.
-  Check CHAOSS Zoom to see the recorded videos. Reach out to any of the maintainers if you need help with this.

**Comment by germonprez** [comment]
Starting the script here: https://docs.google.com/document/d/1zMHxMU28yJeJSoiM_3ieQ5LCA6gVT-oOeJdpbYILjdQ/edit

**Comment by peculiaruc** [comment]
> Starting the script here: https://docs.google.com/document/d/1zMHxMU28yJeJSoiM_3ieQ5LCA6gVT-oOeJdpbYILjdQ/edit

@germonprez Thank you for working on this issue. Kindly update the [Submission. md](https://github.com/chaoss/education/blob/main/Submission.md) file with it. Then send a PR, after which this issue will be closed as completed. Thanks a lot.
