### ISSUE TITLE
Edit CHAOSS Governance Video

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#50]
Description: 
- Edit CHAOSS Governance recorded video content with video editing software.
-  Check CHAOSS Zoom to see the recorded videos. Reach out to any of the maintainers if you need help with this.

**Comment by geekygirldawn** [comment]
Here are the relevant documents for my video:
* Script: https://docs.google.com/document/d/1xl5Mi0YKTF-hr44Wf7TK3Zv5bKARw_eY6PERx2YVr0M/preview
* Presentation: https://docs.google.com/presentation/d/1yRONCzo0hP0xl-K-5ZDmeM_4wX7xHosZcc6dQic1gJ8/preview
* Video recording: https://zoom.us/rec/share/JAzEpdmirE0vHWNKnvvffH-SXwP1oB1tfKmFkx4lkxFnvstgFTXCEEsHvPKBr4-V.WZ4NAVJeVxAkdnGF

The only editing needed is a quick trim at the beginning and end while I'm starting / stopping the recording.

Let me know if you have any questions.

**Comment by peculiaruc** [comment]
@ElizabethN hi! Just checking in with this.
Do you need any help getting started?
Are you able to work on this issue in the next few weeks?
