### ISSUE TITLE
Intro to CHAOSS for Newcomers (Start here?)

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#6]
Description: 
Write a Script for Intro to CHAOSS for Newcomers video

Create an introductory video to onboard Newcomers to CHAOSS:

- High-level overview of all the things at CHAOSS
- Newcomer resources (hangout, community call, tour guides, newcomer bot)
- Link to script
- Link to slide Deck

 Learn more about contributing to this project [here ](https://github.com/chaoss/education/blob/main/Contributing.md)

 Go through the [ReadMe ](https://github.com/chaoss/education/blob/main/README.md) before you start.

**Comment by ElizabethN** [comment]
I plan to work on this Mid-Feb :)

**Comment by peculiaruc** [comment]
> I plan to work on this Mid-Feb :)

Hi @ElizabethN  Are you able to work on this in March?

**Comment by peculiaruc** [comment]
@ElizabethN  I found it here https://www.youtube.com/watch?v=vI5fdMzxNjk . we can go ahead and close this issue, what do you think?
