### ISSUE TITLE
Instructions clarification and where to put content

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/education#61]
I'm still a little confused about the PR part of the instructions from the README (and I suspect that we probably don't really need those PRs at this stage):

> Submission of Script/Recorded Video/Edited Videos;
> To submit your Script/Recorded Video/Edited Videos
> 
> * Create a PR
> * Link the issue you work on to the PR
> * Add the Script/Recorded Video/Edited Video link.
> * Finally, submit the PR.

If you do want PRs ... What file should I use for the PR? 
* Should I create a new file or will there be one file with links to all of the videos?
* If I create a new file, is there a naming convention to use (e.g., governance.md) and should it be in a specific directory (e.g., videos)?

However, I suspect that we don't really need / want PRs at all during this stage? While we are in the process of writing scripts, recording, and editing, it might be better to put links to the content in the issue directly to keep everything together until we have the final, edited videos approved for publication.

We should also keep in mind that most people recording the videos won't actually have links to their recorded videos if they use the CHAOSS Zoom, since only a few of us can log into Zoom to access the recordings, so it might make more sense for people to let us know the date / time of their recording so that someone can log into the CHAOSS Zoom to get the link to the recording and put the link in the issue.

I also think that having a good example of a script, slides, and recorded video might help people get started, and we can add those example links to the instructions. A lot of people work better from examples, and this will help us set the tone for the videos. If you don't already have a good example that you can use in the instructions, I hope to do the governance one in the next day or 2, and we can use that as an example.

I hope this helps and let me know if you have questions about any of this. I'm hoping that if we can make the process easier for people to understand, it will be easier to get people to complete their videos.

**Comment by peculiaruc** [comment]
> I'm still a little confused about the PR part of the instructions from the README (and I suspect that we probably don't really need those PRs at this stage):
> 
> > Submission of Script/Recorded Video/Edited Videos;
> > To submit your Script/Recorded Video/Edited Videos
> > 
> > * Create a PR
> > * Link the issue you work on to the PR
> > * Add the Script/Recorded Video/Edited Video link.
> > * Finally, submit the PR.
> 
> If you do want PRs ... What file should I use for the PR?
> 
> * Should I create a new file or will there be one file with links to all of the videos?
> * If I create a new file, is there a naming convention to use (e.g., governance.md) and should it be in a specific directory (e.g., videos)?
> 
> However, I suspect that we don't really need / want PRs at all during this stage? While we are in the process of writing scripts, recording, and editing, it might be better to put links to the content in the issue directly to keep everything together until we have the final, edited videos approved for publication.
> 
> We should also keep in mind that most people recording the videos won't actually have links to their recorded videos if they use the CHAOSS Zoom, since only a few of us can log into Zoom to access the recordings, so it might make more sense for people to let us know the date / time of their recording so that someone can log into the CHAOSS Zoom to get the link to the recording and put the link in the issue.
> 
> I also think that having a good example of a script, slides, and recorded video might help people get started, and we can add those example links to the instructions. A lot of people work better from examples, and this will help us set the tone for the videos. If you don't already have a good example that you can use in the instructions, I hope to do the governance one in the next day or 2, and we can use that as an example.
> 
> I hope this helps and let me know if you have questions about any of this. I'm hoping that if we can make the process easier for people to understand, it will be easier to get people to complete their videos.

Thanks for this @geekygirldawn . Thats a good suggestion, I will update the README.md file with these awesome suggestions. 
In the Contributing.md file, we added samples of slides etc. https://github.com/chaoss/education/blob/main/Contributing.md.

However, I would also like your sample for the governance one. That will help a lot

**Comment by geekygirldawn** [comment]
As I work on things, I'll drop more questions about the process here in this issue :) 

Question: The slide template has this: 

> Course Title: [Title]
> Lesson/Module: [Lesson/Module #]
> Lesson/Module Title: [Lesson/Module Title]

I'm not sure what to put in those fields. My assumption was that the slides would be used during the video recording, but we might not yet have the numbers. The same issue with the end credits in the template. I won't have those names until after I record the video. At this point, it might be better to streamline the slides to just the minimum that we need while recording (removing slides 7 and 13), since we can put details about the credits and module numbers into the learning management system without including them in the recording. I'm also wondering if we need slide 1 or should we just have slide 6 (example below) as the first slide, since it has the title of the video?

<img width="799" alt="image" src="https://github.com/chaoss/education/assets/1304299/a7c8c529-31e2-43eb-a723-04759ffbe202">

**Comment by peculiaruc** [comment]
> As I work on things, I'll drop more questions about the process here in this issue :)
> 
> Question: The slide template has this:
> 
> > Course Title: [Title]
> > Lesson/Module: [Lesson/Module #]
> > Lesson/Module Title: [Lesson/Module Title]
> 
> I'm not sure what to put in those fields. My assumption was that the slides would be used during the video recording, but we might not yet have the numbers. The same issue with the end credits in the template. I won't have those names until after I record the video. At this point, it might be better to streamline the slides to just the minimum that we need while recording (removing slides 7 and 13), since we can put details about the credits and module numbers into the learning management system without including them in the recording. I'm also wondering if we need slide 1 or should we just have slide 6 (example below) as the first slide, since it has the title of the video?
> 
> <img alt="image" width="799" src="https://private-user-images.githubusercontent.com/1304299/293674988-a7c8c529-31e2-43eb-a723-04759ffbe202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDA3NTYsIm5iZiI6MTcwNDIwMDQ1NiwicGF0aCI6Ii8xMzA0Mjk5LzI5MzY3NDk4OC1hN2M4YzUyOS0zMWUyLTQzZWItYTcyMy0wNDc1OWZmYmUyMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTMwMDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc4NTgxNjMyM2FiN2RjYThjYzgxOGNkYzMzYWJlMjRmM2YzMzViNDZiYzY5YzgxZGJiZWE3N2MxNDE5ODI3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n93P_MLvRjgPP6D-uze9Ai8m27XBZm1-Wsb25FZw_ns">

Slide 6 looks great. I will go through the slide again and revert. Thanks @geekygirldawn

**Comment by peculiaruc** [comment]
> > I'm still a little confused about the PR part of the instructions from the README (and I suspect that we probably don't really need those PRs at this stage):
> > > Submission of Script/Recorded Video/Edited Videos;
> > > To submit your Script/Recorded Video/Edited Videos
> > > 
> > > * Create a PR
> > > * Link the issue you work on to the PR
> > > * Add the Script/Recorded Video/Edited Video link.
> > > * Finally, submit the PR.
> > 
> > 
> > If you do want PRs ... What file should I use for the PR?
> > 
> > * Should I create a new file or will there be one file with links to all of the videos?
> > * If I create a new file, is there a naming convention to use (e.g., governance.md) and should it be in a specific directory (e.g., videos)?
> > 
> > However, I suspect that we don't really need / want PRs at all during this stage? While we are in the process of writing scripts, recording, and editing, it might be better to put links to the content in the issue directly to keep everything together until we have the final, edited videos approved for publication.
> > We should also keep in mind that most people recording the videos won't actually have links to their recorded videos if they use the CHAOSS Zoom, since only a few of us can log into Zoom to access the recordings, so it might make more sense for people to let us know the date / time of their recording so that someone can log into the CHAOSS Zoom to get the link to the recording and put the link in the issue.
> > I also think that having a good example of a script, slides, and recorded video might help people get started, and we can add those example links to the instructions. A lot of people work better from examples, and this will help us set the tone for the videos. If you don't already have a good example that you can use in the instructions, I hope to do the governance one in the next day or 2, and we can use that as an example.
> > I hope this helps and let me know if you have questions about any of this. I'm hoping that if we can make the process easier for people to understand, it will be easier to get people to complete their videos.
> 
> Thanks for this @geekygirldawn . Thats a good suggestion, I will update the README.md file with these awesome suggestions. In the Contributing.md file, we added samples of slides etc. https://github.com/chaoss/education/blob/main/Contributing.md.
> 
> However, I would also like your sample for the governance one. That will help a lot

@geekygirldawn  I have this updated here -> https://github.com/chaoss/education/blob/main/README.md#submission-of-scriptrecorded-videoedited-videos     I will need your review.

**Comment by peculiaruc** [comment]
> > As I work on things, I'll drop more questions about the process here in this issue :)
> > Question: The slide template has this:
> > > Course Title: [Title]
> > > Lesson/Module: [Lesson/Module #]
> > > Lesson/Module Title: [Lesson/Module Title]
> > 
> > 
> > I'm not sure what to put in those fields. My assumption was that the slides would be used during the video recording, but we might not yet have the numbers. The same issue with the end credits in the template. I won't have those names until after I record the video. At this point, it might be better to streamline the slides to just the minimum that we need while recording (removing slides 7 and 13), since we can put details about the credits and module numbers into the learning management system without including them in the recording. I'm also wondering if we need slide 1 or should we just have slide 6 (example below) as the first slide, since it has the title of the video?
> > <img alt="image" width="799" src="https://private-user-images.githubusercontent.com/1304299/293674988-a7c8c529-31e2-43eb-a723-04759ffbe202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDA3NTYsIm5iZiI6MTcwNDIwMDQ1NiwicGF0aCI6Ii8xMzA0Mjk5LzI5MzY3NDk4OC1hN2M4YzUyOS0zMWUyLTQzZWItYTcyMy0wNDc1OWZmYmUyMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTMwMDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc4NTgxNjMyM2FiN2RjYThjYzgxOGNkYzMzYWJlMjRmM2YzMzViNDZiYzY5YzgxZGJiZWE3N2MxNDE5ODI3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n93P_MLvRjgPP6D-uze9Ai8m27XBZm1-Wsb25FZw_ns">
> 
> I will go through the slide again and revert. Thanks @geekygirldawn

@geekygirldawn I have gone through the slide. Here is the updated one https://docs.google.com/presentation/d/1Hhhzau9hc2WJyTbRJWmMFdxFTn4KjBROrevI9JvsZnU/edit#slide=id.g2ab5a4dbc5f_0_5
Kindly add your review too. Thank you.

**Comment by geekygirldawn** [comment]
> @geekygirldawn I have this updated here -> https://github.com/chaoss/education/blob/main/README.md#submission-of-scriptrecorded-videoedited-videos I will need your review.

This looks great, thank you!

**Comment by geekygirldawn** [comment]
> @geekygirldawn I have gone through the slide. Here is the updated one https://docs.google.com/presentation/d/1Hhhzau9hc2WJyTbRJWmMFdxFTn4KjBROrevI9JvsZnU/edit#slide=id.g2ab5a4dbc5f_0_5 Kindly add your review too. Thank you.

I don't seem to have access to this file?

**Comment by peculiaruc** [comment]
> > @geekygirldawn I have gone through the slide. Here is the updated one https://docs.google.com/presentation/d/1Hhhzau9hc2WJyTbRJWmMFdxFTn4KjBROrevI9JvsZnU/edit#slide=id.g2ab5a4dbc5f_0_5 Kindly add your review too. Thank you.
> 
> I don't seem to have access to this file?

I am giving you access now

**Comment by geekygirldawn** [comment]
Can you add one more thing to the template for the script? I was thinking that everyone will have related links that should be shared along with the video in the Learning Management System, and the script is probably the easiest place for people to put those. Here's an example of how I did it for the governance video: https://docs.google.com/document/d/1xl5Mi0YKTF-hr44Wf7TK3Zv5bKARw_eY6PERx2YVr0M/edit

**Comment by peculiaruc** [comment]
> Can you add one more thing to the template for the script? I was thinking that everyone will have related links that should be shared along with the video in the Learning Management System, and the script is probably the easiest place for people to put those. Here's an example of how I did it for the governance video: https://docs.google.com/document/d/1xl5Mi0YKTF-hr44Wf7TK3Zv5bKARw_eY6PERx2YVr0M/edit

Sure, On it

**Comment by geekygirldawn** [comment]
+1 to making the docs read-only.

Thank you so much for all of your help and working with me to clarify how we wanted to do things. I think we're in great shape for people to record videos now, so I'm going to go ahead and close this :)
