### ISSUE TITLE
Intro to Open Source & Collaboration Platforms Video

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#7]
Description:

Write Script for Intro to Open Source & GitHub

The video should cover the intro to open source and GitHub:

- Super High-Level explanation of open source
- Point to Open Source resources
- Point to GitHub resources
- Link to script
- Link to slide deck
- GitLab / GitHub / Other Platforms (Really Sean Thinks BitBucket is the only other platform with traction)"
- Edit Intro to Open Source and Collaboration Platforms recorded video content with video editing software.
-  Check CHAOSS Zoom to see the recorded videos. Reach out to any of the maintainers if you need help with this.

Before you start:

-  Learn more about contributing to this project [here ](https://github.com/chaoss/education/blob/main/Contributing.md)
- Go through the [ReadMe ](https://github.com/chaoss/education/blob/main/README.md) before you start.

**Comment by Anita-ihuman** [comment]
Can I take it up?

**Comment by peculiaruc** [comment]
@Anita-ihuman hi! Just checking in with this. Do you need any help getting started? Are you able to work on this issue in the next few weeks?

**Comment by Anita-ihuman** [comment]
Hello @peculiaruc Yes, I am sure I will be able to come up with something by then

**Comment by Anita-ihuman** [comment]
@peculiaruc  here is a link to the document with the scripts, Please review and leave your comments where neccesary. https://docs.google.com/document/d/1qwVboKEYJRM312MkoJPcu7UjBm-gM9Lye6dagY7j-jQ/edit?usp=sharing

**Comment by peculiaruc** [comment]
Alright. Thank you

**Comment by peculiaruc** [comment]
> @peculiaruc here is a link to the document with the scripts, Please review and leave your comments where necessary. https://docs.google.com/document/d/1qwVboKEYJRM312MkoJPcu7UjBm-gM9Lye6dagY7j-jQ/edit?usp=sharing

@geekygirldawn and @ElizabethN I would like to have you review this script too. Thank you

**Comment by geekygirldawn** [comment]
@Anita-ihuman - thank you so much for doing this - it looks great! I made a few very minor, optional suggestions :)

**Comment by peculiaruc** [comment]
> @Anita-ihuman - thank you so much for doing this - it looks great! I made a few very minor, optional suggestions :)


> @peculiaruc here is a link to the document with the scripts, Please review and leave your comments where neccesary. https://docs.google.com/document/d/1qwVboKEYJRM312MkoJPcu7UjBm-gM9Lye6dagY7j-jQ/edit?usp=sharing

@Anita-ihuman  Thanks again for this submission. Could you please retake a look at the doc?  After effecting the minor suggested change, feel free to send a PR for this Script, including the doc, please.

**Comment by Anita-ihuman** [comment]
How do I send a PR to this script, please? @peculiaruc

**Comment by peculiaruc** [comment]
> How do I send a PR to this script, please? @peculiaruc

Have a look at this file.  https://github.com/chaoss/education/blob/main/Submission.md.  Follow the sample there to add your Script or Video. in the Submission. md file. That way we have all submissions in one place.

You can do it remotely or here.  We can meet up so I can explain further if need be, ping me on slack.

**Comment by peculiaruc** [comment]
Thank you so much @Anita-ihuman . Your PR has been merged. Feel free to record the video as well. Thank you

**Comment by peculiaruc** [comment]
Hi @Anita-ihuman there are a few updates on this issue and on the doc you submitted.  Kindly help update the doc and give edit access. Also there are some comments from Matt. Could you please respond to it?. Thank you

**Comment by harmonyelendu** [comment]
Hi, will love to contribute to this issue

**Comment by harmonyelendu** [comment]
Tasks has been done and a PR submitted

**Comment by peculiaruc** [comment]
> Tasks has been done and a PR submitted

Thanks a lot

**Comment by peculiaruc** [comment]
> Tasks has been done and a PR submitted

Thanks @harmonyelendu for completing this issue, I will go ahead and close it now.
