### ISSUE TITLE
C4GT 2024: Develop a collection of CHAOSS Onboarding Modules for newcomers and open source beginners

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#72]
The goal of this Project is to create high-quality tutorials that will give a clear guide to CHAOSS newcomers or beginners in open source space.

**Objectives**: 

- This onboarding Module will provide a starting point for CHAOSS newcomers and open-source beginners.
- Provide easy navigation and settling of the new CHAOSS contributors.
- A guide on how to quickly start each CHAOSS Project.
- Ease Integration into all  CHAOSS community activities.
- A guide to understand CHAOSS  DEI

**Implementation:**

The expectation is that a script and slide presentation will be created before each video is recorded for all onboarding modules.  Script, Slide presentation and Video samples are provided in the [submission.md file](https://github.com/chaoss/education/blob/main/Submission.md).
- To record a video:
     - Ensure your environment is calm and quiet, and background noise is at a minimum or zero.
     - It should be recorded in a relaxed voice and with a clear tone
     - Recordings should have a transcript, so if you are not working from a pre-written script, make sure the 
      transcription is turned on when you record.
     - Prior to recording, you will need to reserve a block of time on the CHAOSS Zoom for recording. Blocks of 
       time may be reserved in 30-minute increments.
 
    
**Resource Link:**

- CHAOSS:  [CHAOSS Community](https://chaoss.community/)
- Scripting: Write a script or outline to guide your presentation. [Use this sample guide](https://docs.google.com/document/d/1xl5Mi0YKTF-hr44Wf7TK3Zv5bKARw_eY6PERx2YVr0M/edit) and [this is a template](https://docs.google.com/document/d/1jIee4PRQsjF4_nDBxNOcbAxeQ1WA0w5HKOlRc3wdR34/edit). 
- Slides presentation:  [Use this template](https://docs.google.com/presentation/d/1Hhhzau9hc2WJyTbRJWmMFdxFTn4KjBROrevI9JvsZnU/edit#slide=id.g2ab5a4dbc5f_0_5) for a consistent look across our video collection. [Check out this sample](https://docs.google.com/presentation/d/1yRONCzo0hP0xl-K-5ZDmeM_4wX7xHosZcc6dQic1gJ8/preview) before you start
- Recording: You will use the [CHAOSS Zoom](https://zoom.us/my/chaoss) and the recording will start automatically.
- Begin speaking, following your script or outline. [Watch this sample recorded video](https://zoom.us/rec/share/JAzEpdmirE0vHWNKnvvffH-SXwP1oB1tfKmFkx4lkxFnvstgFTXCEEsHvPKBr4-V.WZ4NAVJeVxAkdnGF) for a guide.
- CHAOSS metric model:  [Use this repo](https://github.com/chaoss/wg-metrics-models) and [this](https://chaoss.community/kb-metrics-and-metrics-models)
- CHAOSS metric model video:  [Check this playlist](https://www.youtube.com/playlist?list=PL60k37cxI-HQvwdQWoqtrHhV_tAub5Nm1)

**Microtasks**

To become familiar with CHAOSS onboarding modules, you can start by going through some sample scripts, slide presentations and recorded videos in the [submission.md file](https://github.com/chaoss/education/blob/main/Submission.md).

Once you're familiar with it, you can have a look at the following microtasks.

- Microtask 0:  
Clone the education [repo](https://github.com/chaoss/education)

- Microtask 1:
Go through the [README.md](https://github.com/chaoss/education/blob/main/README.md) file

- Microtask 2:
Check out the [Contributing. md](https://github.com/chaoss/education/blob/main/Contributing.md) file

- Microtask 3:
Read through the submission,md file to see how to create and submit PR for each module.

**_Difficulty:_**   Medium
**_Requirements:_**   Interest in open source education.
**_Recommended:_**   Experience in content creation, documentation and video editing.
**_Mentor:_ **  Peculiar C Umeh, CHAOSS  Education Project Manager

**Comment by Aysha-py** [comment]
Hi @peculiaruc , I would love to work on this. Can you please let me know when you are free? I would love us to have a meeting to make sure I understand clearly what is to be done. 

Thanks

**Comment by peculiaruc** [comment]
Oh! The program is over. This issue is supposed to been closed by now. Sorry about that.
 Kindly look for another

**Comment by Aysha-py** [comment]
Ohh okay. Thank you
