### ISSUE TITLE
CHAOSS Practitioner Guides

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/education#75]
Note: This may be one course or a series of 4 courses. I've split the videos up to be modular with each video containing only one guide. I hope this will make it easier for us to add additional guides in the future. I expect to add a new video every time we create a new guide.

- Script - see speaker notes in presentation
- [Presentation](https://docs.google.com/presentation/d/1W5TkIXGBX1A8mYcY3aUHEvENK8av26S2kvRpm2WxAMA/edit?usp=drive_link)
- [Video: Introduction](https://drive.google.com/file/d/1IavY6YIxRCs6PR4iLpbJew4fa4mo4XPf/view?usp=drive_link)
- [Video: Contributor Sustainability](https://drive.google.com/file/d/1InxWRVVvxPTkEiUvXfL6MgfghsR9URYu/view?usp=drive_link)
- [Video: Responsiveness](https://drive.google.com/file/d/1Is5LPdwqSUdP9C4RLJejKGQHOjXiowLd/view?usp=drive_link)
- [Video: Organizational Participation](https://drive.google.com/file/d/1IzH7tm14ftuLjO0z79zq6dWycU0nTUI9/view?usp=drive_link)

**Comment by peculiaruc** [comment]
> Note: This may be one course or a series of 4 courses. I've split the videos up to be modular with each video containing only one guide. I hope this will make it easier for us to add additional guides in the future. I expect to add a new video every time we create a new guide.
> 
> * Script - see speaker notes in presentation
> * [Presentation](https://docs.google.com/presentation/d/1W5TkIXGBX1A8mYcY3aUHEvENK8av26S2kvRpm2WxAMA/edit?usp=drive_link)
> * [Video: Introduction](https://drive.google.com/file/d/1IavY6YIxRCs6PR4iLpbJew4fa4mo4XPf/view?usp=drive_link)
> * [Video: Contributor Sustainability](https://drive.google.com/file/d/1InxWRVVvxPTkEiUvXfL6MgfghsR9URYu/view?usp=drive_link)
> * [Video: Responsiveness](https://drive.google.com/file/d/1Is5LPdwqSUdP9C4RLJejKGQHOjXiowLd/view?usp=drive_link)
> * [Video: Organizational Participation](https://drive.google.com/file/d/1IzH7tm14ftuLjO0z79zq6dWycU0nTUI9/view?usp=drive_link)

Hi @geekygirldawn , 
Since this issue has been concluded [here](https://github.com/chaoss/education/pull/74), I think I can go ahead to close it.
