### ISSUE TITLE
Record the Context Groups Video

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#76]
Description:

Create a video content on the CHAOSS Context Working Group: This 
- The [Script](https://docs.google.com/document/d/1R4c97vE3FCdjBOm3Jzh74KhTkI764Wj0GCeBdXzI4ow/edit)
- [Slide deck](https://docs.google.com/presentation/d/1t0AcaznIYrsS5YpZD3_7n2xMVmgt_vkMGB-9WGjj1w0/edit#slide=id.g26aba8065f7_0_0)

 Learn more about contributing to this project [here ](https://github.com/chaoss/education/blob/main/Contributing.md)

 Go through the [ReadMe ](https://github.com/chaoss/education/blob/main/README.md) before you start.

**Comment by Young-W1** [comment]
Hi @peculiaruc . I'm interested in this

**Comment by peculiaruc** [comment]
This has been concluded [here](https://github.com/chaoss/education/pull/90). I can go ahead and close this issue
