### ISSUE TITLE
Popular Open-Source Projects

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#94]
Description:
Popular Open Source Projects
- Highlight well-known Open Source Projects like Linux, Apache, Mozilla Firefox, and others.

 Write a Script - Check out the[ samples ](https://github.com/chaoss/education/blob/main/Submission.md)and use this [template](https://docs.google.com/document/d/1jIee4PRQsjF4_nDBxNOcbAxeQ1WA0w5HKOlRc3wdR34/edit)
Create a Slide deck - Find a sample [here](https://github.com/chaoss/education/blob/main/Submission.md), and use this [template](https://docs.google.com/presentation/d/1nnY6dA3RVRaxIULHWGBF7w9PP7eowy2ZfLsxtxm9-9o/edit#slide=id.g2fb06568b76_0_9)
Record a video - [Sample](https://github.com/chaoss/education/blob/main/Submission.md) 

**Additional context**

- Kindly go through the [ReadMe.md](https://github.com/chaoss/education/blob/main/README.md) file. 
- [Contributing.md ](https://github.com/chaoss/education/blob/main/Contributing.md)file contains information that will help you get started
- Choose your preferred [background](https://github.com/chaoss/education#video-background) for your video recording.

**Comment by Aysha-py** [comment]
Hi Peculiar, kindly assign this to me. I will start working on it and be sure to reach out if I have any questions or issues along the line.

**Comment by peculiaruc** [comment]
> Hi Peculiar, kindly assign this to me. I will start working on it and be sure to reach out if I have any questions or issues along the line.

Alright. Thank you

**Comment by peculiaruc** [comment]
This topic has been worked on I will go ahead and close this issue
