### ISSUE TITLE
Open Source In Business

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/education#97]
Description:
Open Source In Business will discuss how businesses can benefit from open-source software with examples(list open-source software that helps businesses) and how businesses can contribute to open source.

1. Write a Script - Check out the[ samples ](https://docs.google.com/document/d/1zMHxMU28yJeJSoiM_3ieQ5LCA6gVT-oOeJdpbYILjdQ/edit)and use this [template](https://docs.google.com/document/d/1jIee4PRQsjF4_nDBxNOcbAxeQ1WA0w5HKOlRc3wdR34/edit)
2. Create a Slide deck - Find a sample [here](https://github.com/chaoss/education/blob/main/Submission.md), and use this [template](https://docs.google.com/presentation/d/1t_oBQhMAtZvvsqTppRj96fbjpokakjiZOdtWIO3NIdY/edit#slide=id.g224756f3bb6_1_0)
3. Record a video - [Sample](https://github.com/chaoss/education/blob/main/Submission.md) 

**Additional context**

- Kindly go through the [ReadMe.md](https://github.com/chaoss/education/blob/main/README.md) file. 
- [Contributing.md ](https://github.com/chaoss/education/blob/main/Contributing.md)file contains information that will help you get started
- Choose your preferred [background](https://github.com/chaoss/education/blob/main/README.md#video-background) for your video recording.

**Comment by Giftea** [comment]
Hi @peculiaruc , can you assign this to me?

**Comment by peculiaruc** [comment]
Hi @Giftea  Are you able to complete this issue before the end of this month?

**Comment by Giftea** [comment]
Yes, I'm almost done @peculiaruc

**Comment by peculiaruc** [comment]
> Yes, I'm almost done @peculiaruc 

That's amazing. 👍

**Comment by peculiaruc** [comment]
Thank you for contributing to the Education Project
